version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_shopdevgo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopdevgo
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
